name: Security checking with Snyk
on:
  workflow_dispatch:

jobs:
  snyk-scan:
    name: Snyk Scan
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@master
      - run: ls -l ${{ github.workspace }}
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        with:
          args: --severity-threshold=high
